name: Sync GitHub → GitLab

on:
  push:
    branches:
      - main

jobs:
  gitlab-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "Surya Suresh"
          git config --global user.email "suryasuresh.p20@gmail.com"

          # Add GitLab remote with secure token access
          git remote add gitlab https://oauth2:glpat-abc123xyz456@gitlab.com/automationrealm/testing.git

          # Push to GitLab
          git push gitlab main --force
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
